=== ihnat-mikhalkovich/FifthTask/WebContent/WEB-INF/resources/books/books.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.task05.com/books"
        xmlns:tns="http://www.epam.task05.com/books">
    <element name="catalog">
        <complexType>
            <sequence>
                <element name="book" type="tns:Book" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Book">
        <sequence>
            <element name="author" type="string"/>
            <element name="title" type="string"/>
            <element name="genre" type="string"/>
            <element name="price" type="double"/>
            <element name="publish_date" type="date"/>
        </sequence>
        <attribute name="id">
            <simpleType>
                <restriction base="string">
                    <pattern value="bk\d+"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
</schema>

=== ihnat-mikhalkovich/FifthTask/WebContent/WEB-INF/resources/books/books.xml
<?xml version="1.0" encoding="utf-8"?>
<tc:catalog xmlns:tc="http://www.epam.task05.com/books"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.epam.task05.com/books books.xsd">
    <book id="bk101">
        <author>Gambardella, Matthew</author>
        <title>XML Developer's Guide</title>
        <genre>Computer</genre>
        <price>44.95</price>
        <publish_date>2000-10-01</publish_date>
    </book>
    <book id="bk102">
        <author>Ralls, Kim</author>
        <title>Midnight Rain</title>
        <genre>Fantasy</genre>
        <price>5.95</price>
        <publish_date>2000-12-16</publish_date>
    </book>
    <book id="bk103">
        <author>Corets, Eva</author>
        <title>Maeve Ascendant</title>
        <genre>Fantasy</genre>
        <price>5.95</price>
        <publish_date>2000-11-17</publish_date>
    </book>
    <book id="bk104">
        <author>Corets, Eva</author>
        <title>Oberon's Legacy</title>
        <genre>Fantasy</genre>
        <price>5.95</price>
        <publish_date>2001-03-10</publish_date>
    </book>
    <book id="bk105">
        <author>Corets, Eva</author>
        <title>The Sundered Grail</title>
        <genre>Fantasy</genre>
        <price>5.95</price>
        <publish_date>2001-09-10</publish_date>
    </book>
    <book id="bk106">
        <author>Randall, Cynthia</author>
        <title>Lover Birds</title>
        <genre>Romance</genre>
        <price>4.95</price>
        <publish_date>2000-09-02</publish_date>
    </book>
    <book id="bk107">
        <author>Thurman, Paula</author>
        <title>Splish Splash</title>
        <genre>Romance</genre>
        <price>4.95</price>
        <publish_date>2000-11-02</publish_date>
    </book>
    <book id="bk108">
        <author>Knorr, Stefan</author>
        <title>Creepy Crawlies</title>
        <genre>Horror</genre>
        <price>4.95</price>
        <publish_date>2000-12-06</publish_date>
    </book>
    <book id="bk109">
        <author>Kress, Peter</author>
        <title>Paradox Lost</title>
        <genre>Science Fiction</genre>
        <price>6.95</price>
        <publish_date>2000-11-02</publish_date>
    </book>
    <book id="bk110">
        <author>O'Brien, Tim</author>
        <title>Microsoft .NET: The Programming Bible</title>
        <genre>Computer</genre>
        <price>36.95</price>
        <publish_date>2000-12-09</publish_date>
    </book>
    <book id="bk111">
        <author>O'Brien, Tim</author>
        <title>MSXML3: A Comprehensive Guide</title>
        <genre>Computer</genre>
        <price>36.95</price>
        <publish_date>2000-12-01</publish_date>
    </book>
    <book id="bk112">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk113">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk114">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk115">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk116">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk117">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk118">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk119">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk120">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk121">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk122">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk123">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk124">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk125">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk126">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk127">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk128">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk129">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk130">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk131">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk132">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk133">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk134">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk135">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk136">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk137">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk138">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk139">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk140">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk141">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk142">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk143">
        <author>info_author_1</author>
        <title>info_title_1</title>
        <genre>info_genre_1</genre>
        <price>0.0</price>
        <publish_date>2018-03-08</publish_date>
    </book>
    <book id="bk144">
        <author>Galos, Mike</author>
        <title>Visual Studio 7: A Comprehensive Guide</title>
        <genre>Computer</genre>
        <price>49.95</price>
        <publish_date>2001-04-16</publish_date>
    </book>
</tc:catalog>
